---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: create-apache-vm-20-job
  namespace: aap
spec:
  connection_secret: aapaccess
  job_template_name: create-apache-vm-20
  extra_vars: 